source 'https://github.com/CocoaPods/Specs.git'

target 'YNLibDemo' do 
	platform :ios, '8.0'
	use_frameworks!
end

target 'YNLibDemoOSX' do 
	platform :osx, '10.10'
	use_frameworks!
end

pod 'YNLib', :git => 'https://github.com/stoprain/YNLib.git'