source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YNLibDemo' do 
	platform :ios, '8.0'
end

target 'YNLibDemoOSX' do 
	platform :osx, '10.10'
end

pod 'YNLib', :git => 'https://github.com/stoprain/YNLib.git'